api_platform:
    # The title of the API.
    title: 'BileMo API Documentation'
    # The description of the API.
    description: 'Private API. The web service of the company BileMo for developers. <br/>The BileMo API allows users to obtain an authentication token for a given customer. This authentication token will then be used in other endpoints to retrieve data from BileMo products.'
    # Set this to false if you want Webby to disappear.
    show_webby: false
    # The version of the API.
    version: '1.0.0'
    defaults:
        pagination_items_per_page: 10 # Default value
        pagination_maximum_items_per_page: 30
        pagination_client_enabled: true
        pagination_enabled: true
        url_generation_strategy: !php/const ApiPlatform\Core\Api\UrlGeneratorInterface::ABS_URL
        #cache_headers:
            #max_age: 0
            #shared_max_age: 3600
            #vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        
        #api_keys:
            #apiKey:
                #name: Authorization
                #type: header
    formats:
        # jsonhal:  ['application/hal+json']
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
        # multipart: ['multipart/form-data']
        # jsonapi:  ['application/vnd.api+json']
        # xml:      ['application/xml', 'text/xml']
        # yaml:     ['application/x-yaml']
        # csv:      ['text/csv']
        # myformat: ['application/vnd.myformat']
    error_formats:
        jsonproblem:                   ['application/problem+json']
        jsonld:                        ['application/ld+json']      # Hydra error formats
        # jsonapi:                       ['application/vnd.api+json']
    enable_re_doc: false
    graphql:
        graphiql:
            enabled: false
        graphql_playground:
            enabled: false
    #http_cache:
        #invalidation:
            #enabled: true
            #varnish_urls: ['%env(VARNISH_URL)%']
        #public: true